
export const jobs = [
    {
        id: 1,
        title: 'Software Engineer',
        company: 'Google',
        location: 'Mountain View, CA',
    },
    {
        id: 2,
        title: 'Software Engineer',
        company: 'Facebook',
        location: 'Menlo Park, CA',
    },
    {
        id: 3,
        title: 'Software Engineer',
        company: 'Apple',
        location: 'Cupertino, CA',
    },
    {
        id: 4,
        title: 'Software Engineer',
        company: 'Amazon',
        location: 'Seattle, WA',
    },
    {
        id: 5,
        title: 'Software Engineer',
        company: 'Microsoft',
        location: 'Redmond, WA',
    },
    {
        id: 6,
        title: 'Software Engineer',
        company: 'Netflix',
        location: 'Los Gatos, CA',
    },
    {
        id: 7,
        title: 'Software Engineer',
        company: 'Tesla',
        location: 'Palo Alto, CA',
    },
    {
        id: 8,
        title: 'Software Engineer',
        company: 'Twitter',
        location: 'San Francisco, CA',
    },
    {
        id: 9,
        title: 'Software Engineer',
        company: 'Uber',
        location: 'San Francisco, CA',
    },
    {
        id: 10,
        title: 'Software Engineer',
        company: 'Lyft',
        location: 'San Francisco, CA',
    },
    {
        id: 11,
        title: 'Software Engineer',
        company: 'Airbnb',
        location: 'San Francisco, CA',
    },
    {
        id: 12,
        title: 'Software Engineer',
        company: 'Slack',
        location: 'San Francisco, CA',
    },
    {
        id: 13,
        title: 'Software Engineer',
        company: 'Pinterest',
        location: 'San Francisco, CA',
    },
    {
        id: 14,
        title: 'Software Engineer',
        company: 'Salesforce',
        location: 'San Francisco, CA',
    },
    {
        id: 15,
        title: 'Software Engineer',
        company: 'Zoom',
        location: 'San Jose, CA',
    },
    {
        id: 16,
        title: 'Software Engineer',
        company: 'Adobe',
        location: 'San Jose, CA',
    },
    {
        id: 17,
        title: 'Software Engineer',
        company: 'Oracle',
        location: 'Redwood City, CA',
    },
]